name: docmate
description: "DocMate - Smart Healthcare Assistant App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  google_sign_in: ^7.2.0
  url_launcher: ^6.2.5
  geolocator: ^13.0.2        # ← লোকেশন ট্র্যাকিংয়ের জন্য যুক্ত করা হয়েছে
  permission_handler: ^11.3.1 # ← ইউজার থেকে সহজে পারমিশন নেওয়ার জন্য যুক্ত করা হয়েছে
  google_maps_flutter: ^2.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/docmate_launcher_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/docmate_launcher_icon.png"
  min_sdk_android: 21
