name: docmate
description: "DocMate - Smart Healthcare Assistant App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  google_sign_in: ^7.2.0
  url_launcher: ^6.2.5
  geolocator: ^13.0.2        # ← লোকেশন ট্র্যাকিংয়ের জন্য যুক্ত করা হয়েছে
  permission_handler: ^11.3.1 # ← ইউজার থেকে সহজে পারমিশন নেওয়ার জন্য যুক্ত করা হয়েছে

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/