// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbjRS-AvL4myI86iFR4W6bksz0qpp9n4k',
    appId: '1:520486284450:web:5c44951bb6bf007c867bfb',
    messagingSenderId: '520486284450',
    projectId: 'docmate-2026',
    authDomain: 'docmate-2026.firebaseapp.com',
    storageBucket: 'docmate-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_jKQm4H5X0A_KnbwyYeUW6rFFk_2-1QY',
    appId: '1:520486284450:android:b7014be57e6ca308867bfb',
    messagingSenderId: '520486284450',
    projectId: 'docmate-2026',
    storageBucket: 'docmate-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVsVCSchhU22QCUbq-4b8HYxHsAYmeLRE',
    appId: '1:520486284450:ios:4c8fb9f993617daf867bfb',
    messagingSenderId: '520486284450',
    projectId: 'docmate-2026',
    storageBucket: 'docmate-2026.firebasestorage.app',
    iosBundleId: 'com.example.docmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVsVCSchhU22QCUbq-4b8HYxHsAYmeLRE',
    appId: '1:520486284450:ios:4c8fb9f993617daf867bfb',
    messagingSenderId: '520486284450',
    projectId: 'docmate-2026',
    storageBucket: 'docmate-2026.firebasestorage.app',
    iosBundleId: 'com.example.docmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbjRS-AvL4myI86iFR4W6bksz0qpp9n4k',
    appId: '1:520486284450:web:29143df763e342cb867bfb',
    messagingSenderId: '520486284450',
    projectId: 'docmate-2026',
    authDomain: 'docmate-2026.firebaseapp.com',
    storageBucket: 'docmate-2026.firebasestorage.app',
  );
}
